[build]
  publish = "."
  functions = "netlify/functions"

# Si ton site est une SPA ou si tu veux éviter les "Page not found"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
